### ISSUE TITLE
Add Louisville.IO

### ISSUE THREAD

**Issue by itzsaga** [itzsaga/slack-list#26]
http://slackin.louisville.io/

**Comment by stoopcjs** [comment]
ill take this one

**Comment by davi3blu3** [comment]
I will work on this issue!

**Comment by davi3blu3** [comment]
I think Louisville.IO has a new location - louisvilletech.org. Seem to be the same org

**Comment by stoopcjs** [comment]
Thanks but I already switched to the Knoxville link because it wasn’t working at first
